name 'razorsedge-tor'
version '0.0.1'

author 'razorsedge'
license 'Apache License, Version 2.0'
project_page 'https://github.com/razorsedge/puppet-tor'
source 'git://github.com/razorsedge/puppet-tor.git'
summary 'Puppet module to manage the Tor onion router.'
description 'https://www.torproject.org/'
dependency 'puppetlabs/stdlib', '>=2.1.0'
